# Generated by Django 4.1.3 on 2022-12-01 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_photos_profile_photo_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
