# Generated by Django 4.1.3 on 2022-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile2.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
